### ISSUE TITLE
ImportError: cannot import name 'MachineReadableFormatError'

### ISSUE THREAD

**Issue by TheLastProject** [fsfe/reuse-tool#103]
```
$ reuse lint
Traceback (most recent call last):
  File "/usr/local/bin/reuse", line 5, in <module>
    from reuse._main import main
  File "/usr/local/lib/python3.6/dist-packages/reuse/_main.py", line 13, in <module>
    from . import (
  File "/usr/local/lib/python3.6/dist-packages/reuse/download.py", line 19, in <module>
    from .project import create_project
  File "/usr/local/lib/python3.6/dist-packages/reuse/project.py", line 15, in <module>
    from debian.copyright import (
ImportError: cannot import name 'MachineReadableFormatError'
```

**Comment by mxmehl** [comment]
Thank you for the report. 

Could you please share
- your operating system and how you installed reuse
- a description in which repository the error occured
- whether this only happens in a specific repository or generally

**Comment by TheLastProject** [comment]
It was running on Travis: https://github.com/Pext/Pext/blob/782e8e09a8e3afc641f0c3f1d17b7f2068649cca/.travis.yml

OS: Ubuntu Xenial (install: `sudo pip install fsfe-reuse`)
Repo: https://github.com/Pext/Pext
Didn't test outside of that, just noticed my build suddenly breaking.

Broken build: https://travis-ci.org/Pext/Pext/jobs/602453833 (October 24)
Working build: https://travis-ci.org/Pext/Pext/builds/601972318 (October 23)

**Comment by mxmehl** [comment]
Hm, cloning and liniting manually on my Arch Linux works flawlessly. We've released a new version 0.5.1 yesterday, but that didn't really change fundamental things.

Is it possible for you to modify your Travis CI to match our [recommended pipeline](https://reuse.software/dev/#travis-ci) using the Docker image?

Otherwise, I am afraid @carmenbianca has to take over here.

**Comment by TheLastProject** [comment]
Well, #101 added that import, which is the main difference between 0.5.0 and 0.5.1.

My best guess is that it's a Python 3.6 vs 3.7 thing. The macOS builds on Travis (using Python 3.7 from Homebrew) were going fine, and Arch Linux, being as up-to-date as it always is, sure also has Python 3.7. The failing build occurred on Python 3.6.

I may look into using the docker image later.

**Comment by carmenbianca** [comment]
I suspect you're using an outdated version of python-debian. Looking into this now.

**Comment by carmenbianca** [comment]
I was right. Gonna make some quick changes:

Will yank 0.5.1 because it breaks backward compatibility.

Will push 0.5.2 with a temporary workaround.

0.6.0 will probably explicitly depend on a `python-debian >= 0.1.35` to prevent this. But not gonna do that yet.

**Comment by carmenbianca** [comment]
Yanked 0.5.1.

Pushed 0.5.2 with a temporary workaround.

Found a better, more generic workaround just after pushing 0.5.2. Because of course. That workaround is now in master. Future version will not need to depend on `python >= 0.1.35`.

Please let me know if 0.5.2 also doesn't work.
